

name: Python application

# triggere the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
        # step 1: check out the code from the repo 
    - name: check out the code 
      uses: actions/checkout@v2

        # step 2: set up py env
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

        # step 3 install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # step 4 run tests 
    
    - name: Test with pytest
      run: pytest
